"""Added Maintenance Module

Revision ID: 09ce23f1a1fd
Revises: 146a05077939
Create Date: 2026-07-12 13:09:01.578232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ce23f1a1fd'
down_revision = '146a05077939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_date', sa.Date(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.drop_column('end_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.drop_column('service_date')

    # ### end Alembic commands ###
