"""Trip Update

Revision ID: 146a05077939
Revises: 950eb6d7a2fc
Create Date: 2026-07-12 12:36:02.722001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146a05077939'
down_revision = '950eb6d7a2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
