"""Added Fuel Module

Revision ID: c43d125504a7
Revises: 09ce23f1a1fd
Create Date: 2026-07-12 13:12:38.768300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43d125504a7'
down_revision = '09ce23f1a1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('price_per_liter', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('odometer', sa.Float(), nullable=False))
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fuel_station',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.alter_column('fuel_station',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('odometer')
        batch_op.drop_column('price_per_liter')
        batch_op.drop_column('fuel_date')

    # ### end Alembic commands ###
