"""Added Expense Module

Revision ID: dffcad9c6d4d
Revises: c43d125504a7
Create Date: 2026-07-12 13:33:20.940961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffcad9c6d4d'
down_revision = 'c43d125504a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('FUEL', 'MAINTENANCE', 'TOLL', 'INSURANCE', 'REPAIR', 'PARKING', 'OTHER', name='expensetype'), nullable=False))
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('expense_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_type', sa.VARCHAR(length=11), nullable=False))
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
